import type { Metadata } from "next";
import { Paytone_One, DM_Sans} from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const paytoneOne = Paytone_One({
  variable: "--font-paytone-one",
  subsets: ["latin"],
  weight: "400",
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${paytoneOne.variable} ${dmSans.variable} antialiased`}
      >
        <Header />
        {children}
      
      </body>
    </html>
  );
}
